name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "7c27b8dc-df20-4e2c-ae3d-73d9dcd3bd23"
